name: Build and Test Java Spring Boot Application 
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
      
      - name: Build with Maven
        run: mvn compile

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          java-version: '22'
      
      - name: Run tests
        run: mvn verify

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: '<YOUR_APP_SERVICE_NAME>'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: './target/*.jar'
      - name: Print message
        run: echo "En construcción ..."
